apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.name }}
  labels:
    app: {{ .Values.persistence.label }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes}}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
