apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ .Values.secret.label }}
type: {{ .Values.secret.type }}
data:
  # Example of environment variable configurations
    {{- range $key, $value := .Values.secret.values }}
    {{ $key }}: "{{ $value }}"
    {{- end }}